# [1週間で学べる！Julia数値計算プログラミング](https://www.kspub.co.jp/book/detail/5282823.html)

## 2日目: 数式をコードにしてみよう
### Julia言語の基本機能

#### 2.2 条件分岐をしてみる：if文

In [1]:
x = 3

3

In [2]:
if x > 4
    y = 3
elseif x < 0
    y = 30
else
    y = 10
end

10

In [3]:
if x > 0 && x < 10
    y = 5
end

5

In [4]:
if 0 < x < 10
    y = 5
end

5

In [5]:
function ReLU(x)
    if x < 0
        zero(x)
    else
        x
    end
end

ReLU (generic function with 1 method)

In [6]:
ReLU(1)

1

In [7]:
ReLU(-4)

0

##### 2.2.1 ifelse関数

In [8]:
ReLU(x) = ifelse(x<0,zero(x),x)

ReLU (generic function with 1 method)

In [9]:
x = -3

-3

In [10]:
if x > 0
    sqrt(x)
else
    x
end

-3

注意
- ifelse(x > 0, sqrt(x), x) はNG
- sqrt(x) と x を事前に評価してから値を返すため

In [11]:
ix = 10

10

In [12]:
jx = ix + 1

11

In [13]:
jx += ifelse(jx > 10, -10, 0)

1

##### 2.2.2 三項演算子
(条件式) ? (Trueの場合の結果) : (Falseの場合の結果)

In [14]:
x = -3

-3

In [15]:
x > 0 ? sqrt(3) : x

-3

#### 2.3 繰り返し計算をしてみる：for文

$\displaystyle f(r) = \sum_{i=1}^n r^{i-1} = \frac{1-r^n}{1-r}$

In [16]:
function f(r,n)
    a = zero(r)
    for i=1:n
        a += r^(i-1)
    end
    return a
end

f (generic function with 1 method)

In [17]:
f(0.5,10)

1.998046875

In [18]:
fanalytic(r,n) = (1-r^n)/(1-r)

fanalytic (generic function with 1 method)

In [19]:
fanalytic(0.5,10)

1.998046875

In [20]:
for i in 1:10
    println("i = $i")
end

i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
i = 9
i = 10


In [21]:
b = ("test", 100)

("test", 100)

In [22]:
for i=b
    println(i)
end

test


100


In [23]:
ran = 1:10

1:10

In [24]:
a = 0
for i in ran
    a += i
end

In [25]:
a

55

In [26]:
ran2 = 1:2:10

1:2:9

In [27]:
ran3 = 1:2.5:10

1.0:2.5:8.5

In [28]:
range(1,10,step=2.5) == 1:2.5:10

true

In [29]:
xs = range(0,2π,length=10)

0.0:0.6981317007977318:6.283185307179586

In [30]:
for i=1:10
    println("cos($(xs[i])) = ", cos(xs[i]))
end

cos(0.0) = 1.0
cos(0.6981317007977318) = 0.766044443118978
cos(1.3962634015954636) = 0.17364817766693041
cos(2.0943951023931953) = -0.4999999999999998
cos(2.792526803190927) = -0.9396926207859083
cos(3.490658503988659) = -0.9396926207859084
cos(4.1887902047863905) = -0.5000000000000004
cos(4.886921905584122) = 0.17364817766692997
cos(5.585053606381854) = 0.7660444431189778
cos(6.283185307179586) = 1.0


In [31]:
collect(xs)

10-element Vector{Float64}:
 0.0
 0.6981317007977318
 1.3962634015954636
 2.0943951023931953
 2.792526803190927
 3.490658503988659
 4.1887902047863905
 4.886921905584122
 5.585053606381854
 6.283185307179586

##### 2.3.1 計算の例：松原振動数の和
$\displaystyle g(x,T) = \lim_{\tau\rightarrow0+}T \sum_{n=-\infty}^{\infty}\frac{e^{i\omega_n\tau}}{i\omega_n-x} = \frac{1}{e^{x/T}+1}$

In [32]:
function g(x,T,nmax;τ=0.01)
    a = 0im # 複素数になるので複素数0imで初期化
    for n = -nmax:nmax
        ωn = π*T*(2n+1)
        a += exp(im*ωn*τ)/(im*ωn-x)
    end
    return real(a*T)
end

g (generic function with 1 method)

In [33]:
xs = range(-1,1,length=10)

-1.0:0.2222222222222222:1.0

In [34]:
T = 0.1

0.1

In [35]:
nmax = 100000

100000

In [36]:
for i=1:10
    println(xs[i],"\t",g(xs[i],T,nmax),"\t",1/(exp(xs[i]/T)+1),"\t",g(xs[i],T,nmax)-1/(exp(xs[i]/T)+1))
end

-1.0	0.989498288411415	0.9999546021312976	-0.010456313719882648
-0.7777777777777778	0.9913302694409194	0.9995812333155556	-0.008250963874636197
-0.5555555555555556	0.990123551768255	0.9961489676440697	-0.0060254158758147325
-0.3333333333333333	0.9618350473721775	0.9655548043337887	-0.003719756961611198


-0.1111111111111111	0.7509941347989852	0.7523361988609284	-0.001342064061943149
0.1111111111111111	0.24743253689074113	0.24766380113907163	-0.00023126424833050385
0.3333333333333333	0.03405360537506296	0.03444519566621118	-0.0003915902911482208
0.5555555555555556	0.0033658873349129608	0.003851032355930255	-0.00048514502101729444
0.7777777777777778	-8.45627268651121e-5	0.0004187666844443735	-0.0005033294113094857


1.0	-0.0004607450598311099	4.5397868702434395e-5	-0.0005061429285335443


##### 2.3.2 目的を達するまで繰り返し続ける：while文


In [37]:
function g2(x,T;τ=0.01,nmax=1000000,eps=1e-8)
    n = 0 # n=0 だけ先に計算
    ωn = π*T*(2n+1)
    a = exp(im*ωn*τ)/(im*ωn-x)
    aold = a
    for n = 1:nmax
        ωn = π*T*(2n+1) # n の項
        a += exp(im*ωn*τ)/(im*ωn-x)
        ωn = π*T*(2(-n)+1) # -n の項
        a += exp(im*ωn*τ)/(im*ωn-x)
        if abs(a-aold)/abs(aold) < eps # 相対誤差がepsより小さくなったらストップ
            println("converged at $n step")
            return T*a
        end
        aold= a
    end
    println("not converged in $nmax step") # nmax ステップ回しても収束しなかったことを言う
    return T*a
end

g2 (generic function with 1 method)

In [38]:
g2(0,0.1;τ=0.001,eps=1e-15)

not converged in 1000000 step


0.49949339668983844 - 1.5915485560452718e-7im

In [39]:
function g2(x,T;τ=0.01,nmax=1000000,eps=1e-8)
    n = 0 # n=0 だけ先に計算
    ωn = π*T*(2n+1)
    a = exp(im*ωn*τ)/(im*ωn-x)
    aold = 10*a
    while abs(a-aold)/abs(a) > eps # この条件が満たされている間回り続ける
        aold = a
        n += 1
        ωn = π*T*(2n+1) # n の項
        a += exp(im*ωn*τ)/(im*ωn-x)
        ωn = π*T*(2(-n)+1) # -n の項
        a += exp(im*ωn*τ)/(im*ωn-x)
    end
    println("converged at $n step")
    return T*a
end

g2 (generic function with 1 method)

In [40]:
g2(0,0.1;τ=0.001,eps=1e-15)

converged at 17845000 step


0.5000283892332869 + 8.918740923376492e-9im

#### 2.4 行列とベクトルを扱う：配列
##### 2.4.1 考えるよりもやってみる
$\vec{b} = \hat{A}\vec{a}$

$
\hat{A} = \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}
$

$\vec{a} = \begin{pmatrix}
1 \\
2 \\
\end{pmatrix}$

In [41]:
a = [1, 2]

2-element Vector{Int64}:
 1
 2

In [42]:
A = [1 2
     3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [43]:
b = A*a

2-element Vector{Int64}:
  5
 11

$\vec{c} = \vec{b}^\dagger\hat{A}\vec{a}$

$
\hat{A} = \begin{pmatrix}
0 & -i \\
i & 0 \\
\end{pmatrix}
$

$
\vec{a} = \frac{1}{\sqrt{2}} \begin{pmatrix}
1 \\
1 \\
\end{pmatrix}
$

$
\vec{b} = \frac{1}{\sqrt{2}} \begin{pmatrix}
1 \\
-1 \\
\end{pmatrix}
$

In [44]:
a = (1/sqrt(2))*[1,1]

2-element Vector{Float64}:
 0.7071067811865475
 0.7071067811865475

In [45]:
b = (1/sqrt(2))*[1,-1]

2-element Vector{Float64}:
  0.7071067811865475
 -0.7071067811865475

In [46]:
A = [0 -im;im 0]

2×2 Matrix{Complex{Int64}}:
 0+0im  0-1im
 0+1im  0+0im

In [47]:
c = b'*A*a

0.0 - 0.9999999999999998im

In [48]:
c = (A'*b)'*a

0.0 - 0.9999999999999998im

##### 2.4.2 ベクトルと行列の定義

In [49]:
a = [1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [50]:
B = [1 2 3 4
     5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [51]:
B = [1 2 3 4;5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [52]:
a = [
    1
    2
    3
    4
]

4-element Vector{Int64}:
 1
 2
 3
 4

In [53]:
a = [1;2;3;4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [54]:
b = [1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [55]:
b*a

1-element Vector{Int64}:
 30

In [56]:
a*b

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

In [57]:
B = zeros(3,4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [58]:
B[1,2] = 3

3

In [59]:
B

3×4 Matrix{Float64}:
 0.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [60]:
function make_matrix(n)
    H = zeros(n, n)
    for i=1:n
        j = i+1
        j += ifelse(j > n, -n, 0)
        H[i,j] = -1
        j = i-1
        j += ifelse(j < 1, n, 0)
        H[i,j] = -1
        H[i,i] = 2
    end
    return H
end

make_matrix (generic function with 1 method)

In [61]:
make_matrix(10)

10×10 Matrix{Float64}:
  2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  -1.0
 -1.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0  -1.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0  -1.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0  -1.0   2.0  -1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0  -1.0   2.0  -1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0  -1.0   2.0  -1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0  -1.0   2.0  -1.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0  -1.0   2.0  -1.0
 -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  -1.0   2.0

In [62]:
A = [1 2 3
4 5 6
7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [63]:
A[1:2,1:2]

2×2 Matrix{Int64}:
 1  2
 4  5

In [64]:
A[2:3,2:3]

2×2 Matrix{Int64}:
 5  6
 8  9

In [65]:
A[[1,3],[1,3]]

2×2 Matrix{Int64}:
 1  3
 7  9

In [66]:
A[:, 1]

3-element Vector{Int64}:
 1
 4
 7

In [67]:
A[1:3,1]

3-element Vector{Int64}:
 1
 4
 7

In [68]:
A[begin:end,1]

3-element Vector{Int64}:
 1
 4
 7

In [69]:
size(A)

(3, 3)

In [70]:
length(A)

9

##### 2.4.3 線形代数計算

In [71]:
using LinearAlgebra

In [72]:
a⋅b # "\cdot" + "Tabキー"で表記可能

30

In [73]:
dot(a,b)

30

In [74]:
a = [3,2im]

2-element Vector{Complex{Int64}}:
 3 + 0im
 0 + 2im

In [75]:
a⋅a

13 + 0im

In [76]:
a'*a

13 + 0im

In [77]:
A = rand(ComplexF64,3,3)

3×3 Matrix{ComplexF64}:
  0.410122+0.888715im  0.0456845+0.838956im   0.50912+0.150915im
   0.96978+0.978767im   0.521893+0.536576im  0.457799+0.112797im
 0.0553968+0.168514im   0.160025+0.534711im  0.519008+0.214143im

In [78]:
A' # ' = 転置＋複素共役

3×3 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
  0.410122-0.888715im   0.96978-0.978767im  0.0553968-0.168514im
 0.0456845-0.838956im  0.521893-0.536576im   0.160025-0.534711im
   0.50912-0.150915im  0.457799-0.112797im   0.519008-0.214143im

In [79]:
transpose(A) # 転置

3×3 transpose(::Matrix{ComplexF64}) with eltype ComplexF64:
  0.410122+0.888715im   0.96978+0.978767im  0.0553968+0.168514im
 0.0456845+0.838956im  0.521893+0.536576im   0.160025+0.534711im
   0.50912+0.150915im  0.457799+0.112797im   0.519008+0.214143im

In [80]:
a = rand(3)
b = rand(3)

3-element Vector{Float64}:
 0.5344925811965274
 0.044186340808045066
 0.47382725089108946

In [81]:
cross(a,b)

3-element Vector{Float64}:
  0.014825782163969063
  0.41761326476560856
 -0.05566812075575122

行列$A$とベクトル$\vec{b}$を与えたときの$\vec{x}$に関する連立方程式：

$A\vec{x}=\vec{b}$

を解く場合は

In [82]:
x = A \ b

3-element Vector{ComplexF64}:
 0.04133248445175036 + 0.32863682293978946im
  -0.563993503239288 - 0.6481928221358672im
  0.7037240210517334 + 0.44206070112250107im

In [83]:
A * x - b

3-element Vector{ComplexF64}:
 -1.1102230246251565e-16 + 5.551115123125783e-17im
   5.551115123125783e-17 - 5.551115123125783e-17im
                     0.0 + 0.0im

固有値問題：

$A\vec{v}_i=e_i\vec{v}_i$

を解く場合は

In [84]:
e, v = eigen(A)

Eigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
values:
3-element Vector{ComplexF64}:
 0.11073592498391338 - 0.3633266921115724im
 0.22140503624955263 + 0.25588271252261224im
   1.118882071419852 + 1.7468775978316875im
vectors:
3×3 Matrix{ComplexF64}:
 -0.342149-0.244143im  -0.258821+0.019491im  0.568783+0.261478im
  0.751244+0.0im       0.0125378+0.447151im  0.717119+0.0im
 -0.497851-0.105379im    0.85588+0.0im       0.301998+0.051514im

In [85]:
A*v[:,1] - e[1]*v[:,1]

3-element Vector{ComplexF64}:
 -3.0531133177191805e-16 - 2.3592239273284576e-16im
  -4.163336342344337e-16 - 3.885780586188048e-16im
  -1.942890293094024e-16 + 2.220446049250313e-16im

その他の例（エルミート行列$B$）：

In [86]:
B=A'*A

3×3 Matrix{ComplexF64}:
  2.88794+0.0im         1.8946+0.315677im  0.962125-0.804857im
   1.8946-0.315677im   1.57775+0.0im       0.646875-0.850262im
 0.962125+0.804857im  0.646875+0.850262im  0.819508+0.0im

In [87]:
e, v = eigen(B)

Eigen{ComplexF64, Float64, Matrix{ComplexF64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 0.04511572941931931
 0.3202625666333715
 4.919812715738077
vectors:
3×3 Matrix{ComplexF64}:
 0.0204988-0.182963im  -0.372234+0.516985im  0.564749-0.491255im
 -0.285476+0.621857im   0.120784-0.464551im   0.34574-0.426456im
  0.705621+0.0im        0.603135+0.0im       0.371923+0.0im

In [88]:
tr(log(B))

-2.6438679606957782 + 0.0im

In [89]:
logdet(B)

-2.6438679606957973 + 7.771561172376096e-16im

##### 2.4.4 行列要素の型

In [90]:
B = zeros(3,3)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia > B[1,2] = 4 + 2im

ERROR: InexactError: Float(4 + 2im)

In [91]:
B = zeros(ComplexF64,3,3)

3×3 Matrix{ComplexF64}:
 0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im

In [92]:
B[1,2] = 4 + 2im

4 + 2im

In [93]:
B = [2 1.2
3 4.1]

2×2 Matrix{Float64}:
 2.0  1.2
 3.0  4.1

In [94]:
B = [2 1.2
3 4.1+1im]

2×2 Matrix{ComplexF64}:
 2.0+0.0im  1.2+0.0im
 3.0+0.0im  4.1+1.0im

In [95]:
B = [2 1
3 4+1im]

2×2 Matrix{Complex{Int64}}:
 2+0im  1+0im
 3+0im  4+1im

In [96]:
B = ones(3,3)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [97]:
B = rand(3,3) # 0-1 までの一様乱数

3×3 Matrix{Float64}:
 0.813409  0.494057  0.473086
 0.278176  0.130459  0.671
 0.840098  0.159359  0.558717

In [98]:
B = randn(3,3) # 標準正規分布に従った乱数

3×3 Matrix{Float64}:
 1.14044   -0.515027   0.49443
 1.58974   -1.48079   -0.614555
 0.595591  -1.62473    1.04447

In [99]:
B = Matrix{Float64}(undef,2,3) # 行列定義（未初期化）

2×3 Matrix{Float64}:
 9.83473e-312  9.83473e-312  9.83473e-312
 9.83473e-312  9.83473e-312  9.83473e-312

##### 2.4.5 行列の一般化：配列の定義

In [100]:
a = zeros(4,4,4)

4×4×4 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [101]:
a = zeros(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)

1×1×1×1×1×1×1×1×1×1×1×1×1×1×1×1×1×1×1×1×1×1 Array{Float64, 22}:
[:, :, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] =
 0.0

In [102]:
C = Array{Float64,3}(undef,2,2,2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 5.0e-324  1.5e-323
 1.0e-323  2.0e-323

[:, :, 2] =
 2.5e-323  NaN
 3.0e-323  NaN

In [103]:
using LinearAlgebra

In [104]:
diagm(1 => [1,2])

3×3 Matrix{Int64}:
 0  1  0
 0  0  2
 0  0  0

In [105]:
diagm(1 => -ones(9),0 => 2*ones(10),-1 => -ones(9))

10×10 Matrix{Float64}:
  2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
 -1.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0  -1.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0  -1.0   2.0  -1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0  -1.0   2.0  -1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0  -1.0   2.0  -1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0  -1.0   2.0  -1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0  -1.0   2.0  -1.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0  -1.0   2.0  -1.0
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  -1.0   2.0

##### 2.4.6 配列の形状の変更

In [106]:
a = [1 2
3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [107]:
a[:]

4-element Vector{Int64}:
 1
 3
 2
 4

In [108]:
a[1,1]

1

In [109]:
a[2,1]

3

In [110]:
a[1,2]

2

In [111]:
a[2,2]

4

In [112]:
reshape(a,(4,1))

4×1 Matrix{Int64}:
 1
 3
 2
 4

In [113]:
reshape(a,(1,4))

1×4 Matrix{Int64}:
 1  3  2  4

In [114]:
b = rand(2,2,2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.406541  0.741562
 0.156916  0.879968

[:, :, 2] =
 0.750854  0.230689
 0.205985  0.186638

In [115]:
reshape(b,(4,2))

4×2 Matrix{Float64}:
 0.406541  0.750854
 0.156916  0.205985
 0.741562  0.230689
 0.879968  0.186638

##### 2.4.7 配列の要素の型

In [116]:
a = 3

3

In [117]:
typeof(a)

Int64

In [118]:
b = rand(3,3)

3×3 Matrix{Float64}:
 0.00170992  0.0607734   0.96514
 0.26579     0.724143    0.145333
 0.341853    0.00764861  0.231453

In [119]:
typeof(b)

Matrix{Float64} (alias for Array{Float64, 2})

In [120]:
B = Matrix{Matrix{Float64}}(undef,2,3)

2×3 Matrix{Matrix{Float64}}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [121]:
B[1,1] = rand(2,3)

2×3 Matrix{Float64}:
 0.261805  0.184017  0.533511
 0.671541  0.312306  0.772909

In [122]:
B[1,2] = rand(1,1)

1×1 Matrix{Float64}:
 0.40718118230097144

In [123]:
B

2×3 Matrix{Matrix{Float64}}:
    [0.261805 0.184017 0.533511; 0.671541 0.312306 0.772909]  …     [0.407181;;]  #undef
 #undef                                                          #undef           #undef

julia > B[1,3]

ERROR: UndefRefError: access to undefined reference

In [124]:
C = Array{Array{Float64},3}(undef,2,2,2)

2×2×2 Array{Array{Float64}, 3}:
[:, :, 1] =
 #undef  #undef
 #undef  #undef

[:, :, 2] =
 #undef  #undef
 #undef  #undef

##### 2.4.8 要素への一括適用：ブロードキャスト
例：

$y(\vec{x})=\hat{W}_2f(\hat{W}_1\vec{x}+\vec{b}_1)+b_2$

- $\vec{x}$: 要素数 $n$ のベクトル
- $\hat{W}_1$: $m\times n$ 行列
- $\vec{b}_1$: 要素数 $m$ のベクトル
- $\hat{W}_2$: $1\times m$ 行列
- $b_2$: スカラー
- $y$: スカラー

Note: 機械学習で使われる隠れ層１層のニューラルネットワークを表す関数

In [125]:
function y1(x,W1,W2,b1,b2)
    xp = W1*x+b1
    m = length(xp)
    f(x) = tanh(x)
    for i=1:m
        xp[i] = f(xp[i])
    end
    wxp = W2*xp
    return wxp[1]+b2
end

y1 (generic function with 1 method)

In [126]:
function y2(x,W1,W2,b1,b2)
    f(x) = tanh(x)
    return W2*f.(W1*x+b1) .+ b2
end

y2 (generic function with 1 method)

In [127]:
n = 2
m = 3
x = rand(n,1)
W1 = rand(m,n)
b1 = rand(m,1)
W2 = rand(1,m)
b2 = 1

1

In [128]:
y1(x,W1,W2,b1,b2)

2.466262067737726

In [129]:
y2(x,W1,W2,b1,b2)

1×1 Matrix{Float64}:
 2.466262067737726

In [130]:
A = [im*π 1
1 im*π]

2×2 Matrix{ComplexF64}:
 0.0+3.14159im  1.0+0.0im
 1.0+0.0im      0.0+3.14159im

In [131]:
exp(A)

2×2 Matrix{ComplexF64}:
 -1.54308+1.49186e-16im   -1.1752+1.07553e-16im
  -1.1752+1.07553e-16im  -1.54308+1.35308e-16im

In [132]:
exp.(A)

2×2 Matrix{ComplexF64}:
    -1.0+1.22465e-16im  2.71828+0.0im
 2.71828+0.0im             -1.0+1.22465e-16im

In [133]:
f(x) = cos(x) + exp(3*x)

f (generic function with 2 methods)

In [134]:
f.(A)

2×2 Matrix{ComplexF64}:
  10.592+3.67394e-16im  20.6258+0.0im
 20.6258+0.0im           10.592+3.67394e-16im

##### 2.4.9 配列の要素の追加と削除

In [135]:
A = []

Any[]

In [136]:
A = Float64[]

Float64[]

In [137]:
A = []

Any[]

In [138]:
push!(A,2)

1-element Vector{Any}:
 2

In [139]:
push!(A,[1,2])

2-element Vector{Any}:
 2
  [1, 2]

In [140]:
push!(A,"test")

3-element Vector{Any}:
 2
  [1, 2]
  "test"

In [141]:
A = Float64[]

Float64[]

In [142]:
push!(A,2)

1-element Vector{Float64}:
 2.0

julia > push!(A,[1,2])

ERROR: MethodError: Cannot 'convert' an object of type Vector{Int64} to an object of type Float64

In [143]:
A = []

Any[]

In [144]:
push!(A,2,3,4)

3-element Vector{Any}:
 2
 3
 4

In [145]:
A = Float64[]

Float64[]

In [146]:
append!(A, [2,3,4])

3-element Vector{Float64}:
 2.0
 3.0
 4.0

In [147]:
A = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [148]:
B = [4,5,6]

3-element Vector{Int64}:
 4
 5
 6

In [149]:
append!(A,B)

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [150]:
A = [1,2]

2-element Vector{Int64}:
 1
 2

In [151]:
append!(A,[3,4],[5,6])

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [152]:
A = [10,20,30]

3-element Vector{Int64}:
 10
 20
 30

In [153]:
deleteat!(A,2)

2-element Vector{Int64}:
 10
 30

In [154]:
A = [10,20,30,40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [155]:
deleteat!(A,[1,2])

2-element Vector{Int64}:
 30
 40

In [156]:
B = [10,20,30,40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [157]:
deleteat!(B,3:4)

2-element Vector{Int64}:
 10
 20