# [1週間で学べる！Julia数値計算プログラミング](https://www.kspub.co.jp/book/detail/5282823.html)

## 2日目: 数式をコードにしてみよう
### Julia言語の基本機能

#### 2.5 型について考える：型と多重ディスパッチ
##### 2.5.1 型とは

In [1]:
a = 1

1

In [2]:
typeof(a)

Int64

In [3]:
typemin(Int64)

-9223372036854775808

In [4]:
typemax(Int64)

9223372036854775807

In [5]:
a = typemin(Int64) - 1

9223372036854775807

In [6]:
typemin(Int8)

-128

In [7]:
typemax(Int8)

127

In [8]:
b = 2.5

2.5

In [9]:
typeof(b)

Float64

In [10]:
a = Int32(8)

8

In [11]:
typeof(a)

Int32

In [12]:
f(x,y) = x*y

f (generic function with 1 method)

In [13]:
f(2,2)

4

In [14]:
f(2,1.5)

3.0

In [15]:
A = [
    1 2
    3 4
]

2×2 Matrix{Int64}:
 1  2
 3  4

In [16]:
B = [10 20
30 40]

2×2 Matrix{Int64}:
 10  20
 30  40

In [17]:
f(A,B)

2×2 Matrix{Int64}:
  70  100
 150  220

In [18]:
f("cat","dog")

"catdog"

julia> f(2,"dog")

ERROR: MethodError: no method mathcing *(::Int64, ::String)

##### 2.5.2 多重ディスパッチ

In [19]:
f(x,y) = x*y

f (generic function with 1 method)

In [20]:
function f(x::Int64,y::String)
    z = ""
    for i=1:x
        z *= y
    end
    return z
end

f (generic function with 2 methods)

In [21]:
f(x) = 10*x

f (generic function with 3 methods)

In [22]:
f(x,y,z) = 10*x*y*z

f (generic function with 4 methods)

In [23]:
f(1)

10

In [24]:
f(1,2,3)

60

In [25]:
methods(f)

# 4 methods for generic function "f" from Main:
 [1] f(x::Int64, y::String)
     @ c:\GitHub\Practice\Julia\1週間で学べる！ Julia数値計算プログラミング\day2-3.ipynb:1
 [2] f(x)
     @ c:\GitHub\Practice\Julia\1週間で学べる！ Julia数値計算プログラミング\day2-3.ipynb:1
 [3] f(x, y)
     @ c:\GitHub\Practice\Julia\1週間で学べる！ Julia数値計算プログラミング\day2-3.ipynb:1
 [4] f(x, y, z)
     @ c:\GitHub\Practice\Julia\1週間で学べる！ Julia数値計算プログラミング\day2-3.ipynb:1

In [26]:
*

* (generic function with 309 methods)

In [27]:
function Base.:*(x::Int64,y::String)
    z = ""
    for i=1:x
        z*=y
    end
    return z
end

In [28]:
*

* (generic function with 310 methods)

In [29]:
3*"dog"

"dogdogdog"

##### 2.5.3 型のヒエラルキー

In [30]:
a = Int32(8)

8

julia> a*"cat"

ERROR: MethodError: no method matching *(::Int32, ::String)

In [31]:
function Base.:*(x::Integer,y::String)
    z = ""
    for i=1:x
        z *= y
    end
    return z
end

In [32]:
a = UInt64(3)

0x0000000000000003

In [33]:
a*"dog"

"dogdogdog"

In [34]:
supertype(Int32)

Signed

In [35]:
supertype(Signed)

Integer

In [36]:
supertype(Integer)

Real

In [37]:
supertype(Real)

Number

In [38]:
supertype(Number)

Any

In [39]:
subtypes(Real)

4-element Vector{Any}:
 AbstractFloat
 AbstractIrrational
 Integer
 Rational

In [40]:
function get_subtypes(type,num)
    types = subtypes(type)
    num += 1
    if length(types) > 1
        for subtypes in types
            println(num*" ",subtypes)
            types = get_subtypes(subtypes,num)
        end
    end
    return types
end

get_subtypes (generic function with 1 method)

In [41]:
get_subtypes(Integer,1)

  Bool
  Signed
   BigInt
   Int128
   Int16
   Int32
   Int64
   Int8
  Unsigned
   UInt128
   UInt16


   UInt32
   UInt64
   UInt8


Type[]

In [42]:
get_subtypes(Real,1)

  AbstractFloat
   BigFloat
   Float16
   Float32
   Float64
  AbstractIrrational
  Integer
   Bool
   Signed
    BigInt


    Int128
    Int16
    Int32
    Int64
    Int8
   Unsigned
    UInt128
    UInt16
    UInt32
    UInt64
    UInt8
  Rational


Type[]

##### 2.5.4 使うと便利な型

In [43]:
a = Set()

Set{Any}()

In [44]:
push!(a,4)

Set{Any} with 1 element:
  4

In [45]:
push!(a,"dog")

Set{Any} with 2 elements:
  4
  "dog"

In [46]:
push!(a,"dog")

Set{Any} with 2 elements:
  4
  "dog"

In [47]:
a = Set{Float64}()

Set{Float64}()

In [48]:
a = Dict()

Dict{Any, Any}()

In [49]:
a["age"] = 4

4

In [50]:
a["name"] = "taro"

"taro"

In [51]:
a[3] = 10

10

In [52]:
a

Dict{Any, Any} with 3 entries:
  "name" => "taro"
  3      => 10
  "age"  => 4

In [53]:
"yamada "*a["name"]

"yamada taro"

#### 2.6 パラメータや変数をまとめる
##### 2.6.1 struct のご利益

In [54]:
x1 = 0.2

0.2

In [55]:
v1 = 1

1

In [56]:
x2 = 0.4

0.4

In [57]:
v2 = 2

2

In [58]:
relative(v1,v2) = v1-v2

relative (generic function with 1 method)

In [59]:
relative(v1,v2)

-1

In [60]:
function relative(vx1,vy1,vz1,vx2,vy2,vz2)
    return vx1-vx2,vy1-vy2,vz1-vz2
end

relative (generic function with 2 methods)

In [61]:
v1 = [2, 1.4, -2.1]

3-element Vector{Float64}:
  2.0
  1.4
 -2.1

In [62]:
v2 = [3.1, 1.2, 0.4]

3-element Vector{Float64}:
 3.1
 1.2
 0.4

In [63]:
relative(v1, v2)

3-element Vector{Float64}:
 -1.1
  0.19999999999999996
 -2.5

In [64]:
m1 = 0.3

0.3

In [65]:
r1 = [0.2,0.5,0.1]

3-element Vector{Float64}:
 0.2
 0.5
 0.1

In [66]:
v1 = [0.3,2,-1]

3-element Vector{Float64}:
  0.3
  2.0
 -1.0

In [67]:
atom1 = [r1,v1,m1]

3-element Vector{Any}:
  [0.2, 0.5, 0.1]
  [0.3, 2.0, -1.0]
 0.3

In [68]:
atom1[3]

0.3

In [69]:
atom1 = Dict()

Dict{Any, Any}()

In [70]:
atom1["r"] = r1

3-element Vector{Float64}:
 0.2
 0.5
 0.1

In [71]:
atom1["v"] = v1

3-element Vector{Float64}:
  0.3
  2.0
 -1.0

In [72]:
atom1["mass"] = m1

0.3

In [73]:
atom1

Dict{Any, Any} with 3 entries:
  "v"    => [0.3, 2.0, -1.0]
  "mass" => 0.3
  "r"    => [0.2, 0.5, 0.1]

In [74]:
atom1["mas"] = 2

2

In [75]:
println(atom1["mass"]*2)

0.6


In [76]:
mutable struct Atom
    r
    v
    mass
end

In [77]:
atom1 = Atom(r1,v1,m1)

Atom([0.2, 0.5, 0.1], [0.3, 2.0, -1.0], 0.3)

In [78]:
atom1.r

3-element Vector{Float64}:
 0.2
 0.5
 0.1

In [79]:
atom1.mass

0.3

In [80]:
atom1.mass = 0.2

0.2

##### 2.6.2 実用的な struct の定義

In [81]:
atom1.mass = [0.2,0.4]

2-element Vector{Float64}:
 0.2
 0.4

In [82]:
mutable struct Atom_new
    r::Array{Float64,1}
    v::Array{Float64,1}
    mass::Float64
end

##### 2.6.3 struct と多重ディスパッチ

In [83]:
a = rand(3,3)

3×3 Matrix{Float64}:
 0.47667   0.879228  0.566605
 0.819519  0.101836  0.906461
 0.957164  0.86883   0.0982806

In [84]:
display(a)

3×3 Matrix{Float64}:
 0.47667   0.879228  0.566605
 0.819519  0.101836  0.906461
 0.957164  0.86883   0.0982806

In [85]:
display(atom1)

Atom([0.2, 0.5, 0.1], [0.3, 2.0, -1.0], [0.2, 0.4])

In [86]:
function Base.display(a::Atom)
    println("r = ",a.r)
    println("v = ",a.v)
    println("mass = ",a.mass)
end

In [87]:
display(atom1)

r = [0.2, 0.5, 0.1]
v = [0.3, 2.0, -1.0]
mass = [0.2, 0.4]


#### 2.7 一通りのセットとしてまとめる：module
##### 2.7.1 include によるコードの整理 

In [88]:
include("./day2/test2.jl")

[20 40; 60 80]
[4 6; 8 10]


##### 2.7.2 関数の上書き

In [89]:
include("./day2/main.jl")

tasu in original.jl
1.4 in original.jl
tasu in main.jl
2.4 in main.jl


##### 2.7.3 module の使用

In [90]:
include("./day2/main_rev.jl")

tasu in original.jl
1.4 in main.jl


In [91]:
module Util
    function util()
        println("util")
    end
end

module Original
    using ..Util
    function originalfunc()
        Util.util()
    end
end

using .Original
Original.originalfunc()

util


In [92]:
using .Original
function originalfunc()
    println("it is not in Original")
end
Original.originalfunc()
originalfunc()

util
it is not in Original


##### 2.7.4 module 内の関数の機能拡張

In [93]:
using .Util
function Util.util(string)
    println(string," outside Util")
end

Util.util()
Util.util("original")

util
original outside Util


In [94]:
module Original
    using ..Util
    function originalfunc()
        Util.util()
        Util.util("original")
    end
end

using .Original
Original.originalfunc()

util
original outside Util


##### 2.7.5 module 名の省略

In [95]:
module Util
    export util
    function util()
        println("util")
    end
end

using .Util
util()

util


In [96]:
using .Util:util

In [97]:
module Util
    export util
    function util()
        println("util")
    end

    function util2()
        println("util2")
    end
end

using .Util:util
Util.util2()

util2


```
module Util
    export util
    function util()
        println("util")
    end
end

using .Util
util()
function util(string)
    println(string," outside Util")
end
```

Error!

##### 2.7.6 using と import の違い --> 省略
「using は借りてくる ⇌ import は自分のものにする」

#### 2.8 微分方程式を解く：パッケージの使用
##### 2.8.1 パッケージのインストールの仕方 --> 省略
Install package = DifferentialEquations
##### 2.8.2 常微分方程式の設定

In [98]:
using DifferentialEquations

In [99]:
f(u,q,t) = 1.01*u # 微分方程式
u0 = 1/2 # 初期値
tspan = (0.0,1.0) # t の範囲
prob = ODEProblem(f,u0,tspan)

ODEProblem with uType Float64 and tType Float64. In-place: false
timespan: (0.0, 1.0)
u0: 0.5

##### 2.8.3 パッケージのヘルプを見る --> 省略
##### 2.8.4 常微分方程式を解く

In [100]:
sol = solve(prob,Tsit5(),reltol=1e-8,abstol=1e-8)

retcode: Success
Interpolation: specialized 4th order "free" interpolation
t: 17-element Vector{Float64}:
 0.0
 0.012407826196308189
 0.042501278333560696
 0.0817804940926822
 0.12887385246570865
 0.18409797482126694
 0.24627458684331965
 0.31479299098506436
 0.38859636482100657
 0.46686178626184555
 0.5487161506239446
 0.633434723668386
 0.7203630271543068
 0.8089580249850934
 0.8987655385980757
 0.9894162242718207
 1.0
u: 17-element Vector{Float64}:
 0.5
 0.5063053789114713
 0.5219304750950854
 0.5430527156531716
 0.5695067808068426
 0.6021743690740426
 0.6412025714747711
 0.6871475333575261
 0.7403258498418478
 0.8012223528078949
 0.8702768771165198
 0.9480214886604926
 1.0350186821189897
 1.1319031558272872
 1.239373504325514
 1.3582039555461738
 1.3728005076225747

In [101]:
nt = 50

50

In [102]:
t = range(0.0, stop=1.0, length=nt) # 0.0 から 1.0 までの nt 点を生成

0.0:0.02040816326530612:1.0

In [103]:
for i=1:nt
    println("t = $(t[i]), solution: $(sol(t[i])), exact solution $(0.5*exp(1.01t[i]))")
end

t = 0.0, solution: 0.5, exact solution 0.5
t = 0.02040816326530612, solution: 0.5104130721711381, exact solution 0.5104130721695938
t = 0.04081632653061224, solution: 0.521043008483123, exact solution 0.521043008483206
t = 0.061224489795918366, solution: 0.5318943253888133, exact solution 0.5318943253848016
t = 0.08163265306122448, solution: 0.5429716333785454, exact solution 0.5429716333784603
t = 0.10204081632653061, solution: 0.5542796390000767, exact solution 0.5542796389872846
t = 0.12244897959183673, solution: 0.5658231467495113, exact solution 0.5658231467531065
t = 0.14285714285714285, solution: 0.5776070613117803, exact solution 0.5776070612778401
t = 0.16326530612244897, solution: 0.5896363893061378, exact solution 0.5896363893073463
t = 0.1836734693877551, solution: 0.6019162418595128, exact solution 0.6019162418586985
t = 0.20408163265306123, solution: 0.614451836460907, exact solution 0.614451836391749
t = 0.22448979591836735, solution: 0.627248499015715, exact solution 0.

#### 2.9 数式処理（代数演算）をする：他の言語のライブラリを呼ぶ
##### 2.9.1 Python ライブラリの sympy を使う

In [104]:
using PyCall

In [105]:
PyCall.pyversion

v"3.10.12"

In [ ]:
PyCall.pyprogramname

In [ ]:
pyimport_conda("sympy","sympy")

In [ ]:
sympy = pyimport("sympy")

In [109]:
x = sympy.Symbol("x") # PyObject x

PyObject x

In [110]:
y = sympy.Symbol("y")

PyObject y

In [111]:
b = (x+1)^2

PyObject (x + 1)**2

In [112]:
sympy.expand(b)

PyObject x**2 + 2*x + 1

In [113]:
z = b.subs(x,2)

PyObject 9

In [114]:
convert(Int64,z)

9

##### 2.9.2 SymPy.jl を使ってみる

In [115]:
using SymPy

In [116]:
x = symbols("x")

x

In [117]:
y = symbols("y")

y

In [118]:
b = (x+1)^2

       2
(x + 1) 

In [119]:
expand(b)

 2          
x  + 2*x + 1

In [120]:
b.subs(x,2)

9